# Site settings
title: The Loop
email: ""
description: "A recurring open source hacking meet up."
baseurl: ""
url: "http://loopdev.github.io"
github_username:  ""

# Build settings
markdown: kramdown
permalink: pretty

# Github defaults
github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-paginate
