# Site settings
title: "The Loop"
email: ""
description: "A recurring open source hacking meet up in HK."
baseurl: ""
url: "http://loopdev.github.io"
github_username:  ""
facebook_group: "https://www.facebook.com/groups/loop.dev"

# Build settings
markdown: kramdown
permalink: pretty

# Github defaults
github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-paginate
